### ISSUE TITLE
Cambiare's keyboard design

### ISSUE THREAD

**Issue by GFHK-SDGM** [ltgcgo/octavia#17]
The current design is much less legible for a person who has actually learned how to play a piano, compared to the keyboard in Cambiare alpha, which resembles real piano keys. In order to make the keyboard more legible, as well as taking technical limitations on Cambiare beta into consideration, I propose the following design instead:
* Shorten the display length of each black key
* Add an additional scale between E and F.

And here's what my proposal looks like:
![cambiare_keys](https://github.com/ltgcgo/octavia/assets/121885686/d1c21ea7-4694-4d73-a646-69f79d4c69a6)

**Comment by PoneyClairDeLune** [comment]
This is being addressed in #18. Please refer to said issue for further updates.

Currently being implemented as "comb" style keys.
