### ISSUE TITLE
SC55 Bitmap display SysEx command misinterpretation (Stop displaying bitmap shows blank for few sec instead)

### ISSUE THREAD

**Issue by JOELwindows7** [ltgcgo/octavia#42]
# Misinterpretation
There is an interpretation error for emulated SC display on the demo (https://gh.ltgc.cc/octavia/test/fakeSc.htm ), that the `Stop displaying Bitmap` command here is interpreted as `Blank bitmap` for a few seconds, where it should've stop displaying bitmap **& immediately return displaying channel spectrums**.

## Samples

On my recording: https://odysee.com/@X0P1R4T3-33NSVREENMNT-0FFICIAL:f/TOPACK_Robbi985:6 Notice when the Octavia receives `Stop displaying bitmap` command, it shows empty bitmap until few seconds, instead of immediately going back to channel spectrums

On Robbi985's actual Roland SC88Pro: https://youtu.be/qrhnjT8MYWo?si=GAC9WMOoG9g6NbAJ the `Stop displaying bitmap` does indeed make the display immediately shows spectrum again.

The MIDI pack itself: https://odysee.com/@X0P1R4T3-33NSVREENMNT-0FFICIAL:f/TOPACK_Robbi985:6 which file was `Manual Download at Robbi985.7z/SC88 MIDI/BPKM.mid`. for the SC generator tool, it's in the other 7z file, SoundCanvas display tool.

**Comment by JOELwindows7** [comment]
**turns out this is a problem on the core itself!** all demos that interprets Roland SC display command uses this SC display emulation part of it, & this one command that's interpreted wrong by the core itself.

**Comment by PoneyClairDeLune** [comment]
Thanks for raising the issue! Fixed in [`43ab0a1`](https://github.com/ltgcgo/octavia/commit/43ab0a1739ad1a9e8d1f93ba5ea4bcc43357fe98).
