### ISSUE TITLE
MU Series LCD Color

### ISSUE THREAD

**Issue by now-its-dark** [ltgcgo/octavia#9]
Hi there! 

It seems like the color of the fake MU LCD in Octavia is derived from how the screen appears in a photo—

I've noticed that the display appears overly green when photographed, but is much closer to [safety yellow](https://www.pantone.com/connect/13-0630-TN) in reality. It's a bit difficult to get an accurate photographic representation of the color, as it requires overriding the white balance toward red by quite a bit (making everything else look much too red hehe):

![MU_LCD_COLOR](https://user-images.githubusercontent.com/5728860/218357837-159ae62f-c7ed-4d2b-b5a0-9be19eb076f3.png)

#C9E10A does a pretty good job of replicating the true color I think:

![fakeMU_recolored](https://user-images.githubusercontent.com/5728860/218294318-cac844d5-a9b3-4c2b-975d-60e35e0a0c0f.png)

I compared on multiple devices (mac & windows) and this was the most accurate across all of them.
This is assuming that the color of the LCD is the same for all MU devices, as I only have an MU2000 to reference, but pretty sure they use the same panel.

**Comment by PoneyClairDeLune** [comment]
Thank you!
Not sure about the Pantone colour "Safety Yellow", since it appears to be way too yellow... But the colour in the picture seems to be a pretty good candidate. I settled on `#c1ff0a` instead:
![image](https://user-images.githubusercontent.com/88174309/218310538-e291facf-c867-444d-96de-3ad182faa8ee.png)

**Comment by now-its-dark** [comment]
Whoops, I somehow left out the actual photo! The image there was a recolored version of the Octavia screen. Just added back the photo I had meant to include. 

The screen is actually yellow, far more than is intuitive– it's weird, in my mind, I think of it as green, but looking at it, it really is a greenish yellow color as depicted.

**Comment by PoneyClairDeLune** [comment]
Just pushed a new commit changing the MU backlight colour. Does it now look authentic enough?

**Comment by now-its-dark** [comment]
Oh cool! I think it's a very close match to the original screen color, looks great!

**Comment by PoneyClairDeLune** [comment]
Thanks! The issue is now closed, but feel free to open it back up in case further changes are considered needed.
